#!/usr/bin/env bash
# 
# PHASE 3: Data Validation Checklist
# ==================================
# 
# You're NOT building anything else.
# You're collecting evidence that your edge is real.
#
# Run this command daily to check your metrics:
# curl -s http://localhost:3000/api/clv | jq '.systemState, .rolling50'
#

CHECKPOINT_METRICS=(
  "systemState.state"
  "rolling50.avgClv"
  "rolling50.beatingMarketPct"
  "rolling50.count"
  "allTime.expectedProfit"
  "allTime.actualProfit"
  "segmentation.bySignalQuality"
)

echo "================================"
echo "  PHASE 3: MONITORING CHECKLIST"
echo "================================"
echo ""
echo "System is collecting data. DO NOT INTERFERE."
echo ""
echo "YOUR ONLY JOB RIGHT NOW:"
echo "1. Let cron run (/api/generate every hour)"
echo "2. Watch these 3 metrics daily:"
echo ""
echo "   ✓ Rolling CLV (last 50 bets)"
echo "     Target: > 0"
echo "     Command: curl -s http://localhost:3000/api/clv | jq '.rolling50.avgClv'"
echo ""
echo "   ✓ Beat Rate (% beating closing line)"
echo "     Target: 55-60%"
echo "     Command: curl -s http://localhost:3000/api/clv | jq '.rolling50.beatingMarketPct'"
echo ""
echo "   ✓ Signal Quality Breakdown"
echo "     See: HIGH vs NORMAL edge distribution"
echo "     Command: curl -s http://localhost:3000/api/clv | jq '.segmentation.bySignalQuality'"
echo ""
echo "================================"
echo "  CHECKPOINT TIMELINE"
echo "================================"
echo ""
echo "0-50 bets   → Ignore, noise expected"
echo "50-100 bets → CLV stabilizing"
echo "100-150 bets → DECISION WINDOW"
echo ""
echo "================================"
echo "  150-BET DECISION TREE"
echo "================================"
echo ""
echo "🟢 GREEN (CLV > 0)"
echo "  → Edge is real"
echo "  → Scale stakes by 20%"
echo "  → Begin building AI layer"
echo ""
echo "🟡 AMBER (CLV ≈ 0)"
echo "  → Tighten filters"
echo "  → Increase EV threshold to 0.08"
echo "  → Increase edge threshold to 0.04"
echo ""
echo "🔴 RED (CLV < 0)"
echo "  → Edge is fake or market shifted"
echo "  → STOP BETTING"
echo "  → Rebuild model"
echo ""
echo "================================"
echo "  DO NOT DO THESE THINGS"
echo "================================"
echo ""
echo "❌ Add AI layer"
echo "❌ Build mobile dashboard"
echo "❌ Create execution bot"
echo "❌ Expand to multi-sport"
echo "❌ Change thresholds midway"
echo "❌ Manually place bets"
echo "❌ Override system decisions"
echo ""
echo "================================"
echo "  ONLY SAFE ACTION"
echo "================================"
echo ""
echo "✅ Monitor metrics"
echo "✅ Track CLV"
echo "✅ Log signal quality"
echo "✅ Let cron run"
echo ""
echo "================================"
